### PR TITLE
Revision by Vanesa

### PR DESCRIPTION
**Pull request by vanesascode**
Hi there, this is my revision of David's project. 

I found it all very well done: 

 - Variable names are understandable.
 - Comments are appropiate to follow the code.
 - The code is clean and readable.
 - The website in general is cool and very clean, and funny!

### CODE REVIEW

**Comment by vanesascode** [comment]
Great! I'm glad you liked it!

**Comment by gdwhittaker94** [comment]
Thanks Vanesa!

**Comment by vanesascode** [comment]
Thank you David!

**Comment by gdwhittaker94** [comment]
Muchas de nadas!

**Pull request merged**
